version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - 9200:9200


  interview-project:
    image: edu.training.interview-project:1.0.0
    container_name: interview-project
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
